#ifndef __guifrmMain__
#define __guifrmMain__

/**
@file
Subclass of frmMain, which is generated by wxFormBuilder.
*/

#include "gui.h"
#include <tools.h>
#include <vector>
#include <node.h>

//// end generated include

/** Implementing frmMain */
class guifrmMain : public frmMain
{
	public:
		/** Constructor */
		guifrmMain( wxWindow* parent );
	//// end generated class members

	    void DrawCircle(wxMouseEvent &event) override;
		void AddMode( wxCommandEvent& event ) override;

	private:

		Mode mode;
		std::vector<Node> nodes;

};


#endif // __guifrmMain__
